export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_PRODCUT_IN_CART = 'DELETE_PRODCUT_IN_CART';
export const UPDATE_PRODCUT_IN_CART = 'UPDATE_PRODCUT_IN_CART';
export const CHANGE_MESSAGE = 'CHANGE_MESSAGE';